### ISSUE TITLE
Crate fails to build with latest Rust compiler

### ISSUE THREAD

**Issue by gmes78** [cholcombe973/libparted-sys#4]
Compilation fails with the following error while compiling `syntex_syntax`, dependency of `bindgen` 0.30:

```
error[E0423]: expected function, tuple struct or tuple variant, found struct `ast::Name`
   --> /home/joaquim/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/symbol.rs:146:27
    |
146 |                       name: ast::Name($index),
    |                             ^^^^^^^^^
...
165 | / declare_keywords! {
166 | |     // Invalid identifier
167 | |     (0,  Invalid,        "")
168 | |
...   |
231 | |     (56, CrateRoot, "{{root}}")
232 | | }
    | |_- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
This error doesn't happen with newer versions of `bindgen`.

**Comment by cholcombe973** [comment]
Sounds like bindgen needs updating on the crate.

**Comment by cholcombe973** [comment]
@gmes78 could you check if #5 fixes your issue?

**Comment by gmes78** [comment]
Yes, that fixes it.

**Comment by gmes78** [comment]
That said, the generated bindings are different. For example, `PedPartitionType` is an enum in the current version of this crate, but after updating bindgen it becomes a `u32`, with the enum variants turning into constants, like `_PedPartitionType_PED_PARTITION_NORMAL`.

**Comment by cholcombe973** [comment]
Ah alright so we'll have to do a major version change then.  I was wondering if it was going to do that.

**Comment by cholcombe973** [comment]
@gmes78 I've pushed 0.2.0.  I'm assuming you're building a safe library on top of these bindings?

**Comment by gmes78** [comment]
[`libparted`](https://crates.io/crates/libparted) already exists, I'm just trying to use that (or rather, to make it work again).

Anyway, thank you for the quick fix.
